# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('brandID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, unique=True)),
                ('address', models.CharField(default='地址未录入', max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('catID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('couponID', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('listPrice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('product', models.CharField(max_length=16, null=True)),
                ('stat', models.CharField(choices=[('1', 'onSale'), ('2', 'expired'), ('3', 'used'), ('4', 'store')], default='store', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='couponList',
            fields=[
                ('listID', models.AutoField(primary_key=True, serialize=False)),
                ('stat', models.CharField(choices=[('1', 'own'), ('2', 'sold'), ('3', 'brought'), ('4', 'onSell'), ('5', 'like')], max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='massage',
            fields=[
                ('messageID', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('userID', models.CharField(max_length=16, null=True)),
                ('content', models.CharField(max_length=128, null=True)),
                ('time', models.TimeField(null=True)),
                ('messageCat', models.CharField(choices=[('1', '上架的优惠券被购买'), ('2', '上架的优惠券即将过期'), ('3', '上架的优惠券已过期'), ('4', '关注的优惠券即将过期'), ('5', '关注的优惠券已被购买'), ('6', '我的优惠券即将过期'), ('7', '我的优惠券已过期'), ('8', '系统通知')], max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('ID', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('nickname', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('phoneNum', models.CharField(max_length=16, unique=True)),
                ('gender', models.CharField(choices=[('1', '男'), ('2', '女')], max_length=2)),
                ('avatar', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='listItem',
            fields=[
                ('listID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='UHuiWebApp.couponList')),
                ('couponID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='UHuiWebApp.coupon')),
            ],
        ),
        migrations.AddField(
            model_name='limit',
            name='couponID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UHuiWebApp.coupon'),
        ),
        migrations.AddField(
            model_name='couponlist',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UHuiWebApp.user'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='brandID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UHuiWebApp.brand'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='catID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UHuiWebApp.category'),
        ),
    ]
