# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UHuiWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='brandID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bID', to='UHuiWebApp.brand'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='catID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cID', to='UHuiWebApp.category'),
        ),
        migrations.AlterUniqueTogether(
            name='listitem',
            unique_together=set([('listID', 'couponID')]),
        ),
        migrations.AlterModelTable(
            name='listitem',
            table='UHuiWebApp_listItem',
        ),
    ]
