# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UHuiWebApp', '0002_auto_20170714_1039'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listitem',
            unique_together=set([]),
        ),
        migrations.AlterModelTable(
            name='listitem',
            table=None,
        ),
    ]
