# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UHuiWebApp', '0003_auto_20170714_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNum',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
