from django.conf.urls import url

from . import views
from apiForAndroid import views as androidViews

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^user$', views.userPage, name='user'),
    url(r'^mobile_mycoupons$', views.myCouponsPage, name='mycoupons'),
    url(r'^search$', views.search, name='search'),
    url(r'^commodity$', views.commodity, name='commodity'),
    url(r'^mobile_appraisement$', views.mobile_appraisement, name='mobile_appraisement'),
    url(r'^mobile_user_setting$', views.mobile_user_setting, name='mobile_user_setting'),
    url(r'^mobile_user_wallet$', views.mobile_user_wallet, name='mobile_user_wallet'),
    url(r'^mobile_sell_final$', views.mobile_sell_final, name='mobile_sell_final'),
    url(r'^mobile_couponsmessage$', views.mobile_couponsmessage, name='mobile_couponsmessage'),

    url(r'^mobile_myboughtcoupons$', views.mobile_myboughtcoupons, name='mobile_myboughtcoupons'),
    url(r'^mobile_mysoldcoupons$', views.mobile_mysoldcoupons, name='mobile_mysoldcoupons'),
    url(r'^mobile_mylikecoupons$', views.mobile_mylikecoupons, name='mobile_mylikecoupons'),
    url(r'^mobile_login$', views.mobile_login, name='mobile_login'),
    url(r'^mobile_index$', views.mobile_index, name='mobile_index'),
    url(r'^mobile_user$', views.mobile_user, name='mobile_user'),

    url(r'^post_login$', views.post_login, name='post_login'),
    url(r'^post_signup$', views.post_signUp, name='post_signUp'),
    url(r'^post_logout$', views.post_logout, name='logout'),
    url(r'^post_sendEmailVerifyCode$', views.post_sendEmailVerifyCode, name='post_sendEmailVerifyCode'),
    url(r'^post_sendMobileVerifyCode$', views.post_sendMobileVerifyCode, name='post_sendMobileVerifyCode'),
    url(r'^post_modifyUserInfo$', views.post_modifyUserInfo, name='post_modifyUserInfo'),
    url(r'^post_search$', views.post_search, name='post_search'),
    url(r'^mobile_search$', views.mobile_search, name='mobile_search'),
    url(r'^post_getUserCoupon$', views.post_getUserCoupon, name='post_getUserCoupon'),
    url(r'^post_getCouponForMobileIndex$', views.post_getCouponForMobileIndex, name='post_getCouponForMobileIndex'),
    url(r'^post_getCouponByCatIndex$', views.post_getCouponByCatIndex, name='post_getCouponByCatIndex'),
    url(r'^emailVerification/', views.emailVerification, name='emailVerification'),
    url(r'^post_like$', views.post_like, name='post_like'),
    url(r'^post_dislike$', views.post_dislike, name='post_dislike'),
    url(r'^post_buy$', views.post_buy, name='post_buy'),
    url(r'^post_presearch$', views.post_presearch, name='post_presearch'),
    url(r'^post_changeAvatar$', views.post_changeAvatar, name='post_changeAvatar'),
    url(r'^post_putOnSale$', views.post_putOnSale, name='post_putOnSale'),
    url(r'^post_putOffSale$', views.post_putOffSale, name='post_putOffSale'),
    url(r'^post_buyCredit$', views.post_buyCredit, name='post_buyCredit'),
    url(r'^post_couponDetail$', views.post_couponDetail, name='post_couponDetail'),
    url(r'^post_getCouponByCat$', views.post_getCouponByCat, name='post_getCouponByCat'),

    url(r'^loginForAndroid$', androidViews.loginForAndroid, name='loginForAndroid'),
    url(r'^signUpForAndroid$', androidViews.signUpForAndroid, name='signUpForAndroid'),
    url(r'^sendMessage$', androidViews.sendMessage, name='sendMessage'),
    url(r'^searchForAndroid$', androidViews.searchForAndroid, name='searchForAndroid'),
    url(r'^couponDetail$', androidViews.couponDetail, name='couponDetail'),
    #url(r'^ownerDetail$', androidViews.ownerDetail, name='ownerDetailForAndroid'),
    url(r'^returnInformation', androidViews.returnInformation, name='returnInformation'),
    url(r'^getBoughtList$', androidViews.getBoughtList, name='getBoughtList'),
    url(r'^getStoreList$', androidViews.getStoreList, name='getStoreList'),
    url(r'^getOnSaleList$', androidViews.getOnSaleList, name='getOnSaleList'),
    url(r'^getLikeList$', androidViews.getLikeList, name='getLikeList'),
    url(r'^getSoldList$', androidViews.getSoldList, name='getSoldList'),
    url(r'^likeCoupon$', androidViews.likeCoupon, name='likeCoupon'),
    url(r'^dislikeCoupon$', androidViews.dislikeCoupon, name='dislikeCoupon'),
    url(r'^addCoupon$', androidViews.addCoupon, name='addCoupon'),
    url(r'^updatePassword$', androidViews.updatePassword, name='updatePassword'),
    url(r'^buyCoupon$', androidViews.buyCoupon, name='buyCoupon'),
    url(r'^getUsedList$', androidViews.getUsedList, name='getUsedList'),
    url(r'^updateAvatar$', androidViews.updateAvatar, name='updateAvatar'),
    url(r'^preSearch$', androidViews.preSearch, name='preSearch'),
    url(r'^updateUserInformation$', androidViews.updateUserInformation, name='updateUserInformation'),
    url(r'^getBanner$', androidViews.getBanner, name='getBanner'),
    url(r'^homepageCoupon$', androidViews.homepageCoupon, name='homepageCoupon'),
    url(r'^searchInCategory$', androidViews.searchInCategory,
        name='post_searchInCategory'),
    url(r'^searchByCategory$', androidViews.searchByCategory, name='post_searchByCategory'),
    url(r'^changeCouponState$', androidViews.changeCouponState, name='post_changeCouponState'),
    url(r'^checkUsername$', androidViews.checkUsername, name='post_checkUsername'),
    url(r'^sellerInformation$', androidViews.sellerInformation, name='post_sellerInformation'),
    url(r'^_getValue$', androidViews.getValue, name='post_getValue'),
    url(r'^updatePhoneOrEmail$', androidViews.updatePhoneOrEmail, name='post_updatePhoneOrEmail'),
    url(r'^preSearchInCategory$', androidViews.preSearchInCategory, name='post_preSearchInCategory'),

]
